### PR TITLE
Add bfloat support

### PR DESCRIPTION
**Pull request by bhack**
See https://github.com/pytorch/pytorch/pull/121087#issuecomment-1975614324

### CODE REVIEW

**Comment by bhack** [comment]
Is there any CI action?

**Comment by ClementPinard** [comment]
No, this package is quite old ^^

But you are right to mention that, you should update the README with the version you tested it with. Presumably the first pytorch that features the `AT_DISPATCH_FLOATING_TYPES_AND2` function in its C API

**Review by bhack — COMMENTED** [review]
I've switched the required to Pytorch min 2.0.0. I suppose it is reasonable for main.

**Comment by bhack** [comment]
I switched to pytorch 2.1.0 as the current readme was already on this version.

**Comment by ClementPinard** [comment]
thanks !

**Pull request merged**
